controllers/PaymentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Transaction;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig;
use GlobalPayments\Api\Services\HostedService;
use GlobalPayments\Api\Entities\Exceptions\ApiException;


class PaymentController extends Controller
{   
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                	[
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    // 'data-post' => ['post'],
                    'process-payment' => ['post']
                ],
            ],
        ];
    }

	public function beforeAction($action)
	{            
	    if ($action->id == 'process-payment') {
	        $this->enableCsrfValidation = false;
	    }

	    return parent::beforeAction($action);
	}

	 /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
    	//echo "uyu"; die;
        return $this->render('index');
    }

    public function actionDataPost()
    {
    	$post = Yii::$app->request->post();
    	if(isset($post) && !empty($post)){
    		$model = new Transaction();
    		$model->name = $post['Name'];
    		$model->email = $post['Email'];
    		$model->phonenumber = $post['PhoneNumber'];
    		$model->order_id = $post['ORDER_ID'];
    		$model->amount = $post['AMOUNT'];
    		$model->accountrefference = $post['ORDER_ID'];
    		$model->currency = Yii::$app->params["currency"];
    		$model->auto_settle_flag ="1";
    		$model->comments = $post['Comments'];

    		if ($model->save()) {
    			$data =[
						  "MERCHANT_ID" =>Yii::$app->params["merchantId"],
						  "ACCOUNT"=> Yii::$app->params["accountId"],
						  "AMOUNT"=> $model->amount,
						  "CURRENCY"=>$model->currency,
						  "AUTO_SETTLE_FLAG"=>$model->auto_settle_flag,
						  "PM_METHODS"=>"cards"
						];
    			$data["ORDER_ID"] = substr(str_shuffle('abcdefghijklmnopqrstuvwxyz0123456789'), 0, 22);
				$data["TIMESTAMP"] = date("YmdHis");
				$data["SHA1HASH"] = $this->generateHash($data, Yii::$app->params["merchantSecret"]);
	            return $this->render('card-holder',['model' => $model, 'data' => json_encode($data)]);
	        }
    	}
    	return $this->render('status',['sucess' => false, 'parsedResponse' => (object) ['responseMessage' => 'Invalid Data']]);
    }

    public function actionProcessPayment($id=0){
    	//echo"test"; die;
    	$config = new GpEcomConfig();
		$config->merchantId = Yii::$app->params["merchantId"];
		$config->accountId = Yii::$app->params["accountId"];
		$config->sharedSecret = Yii::$app->params["merchantSecret"];
		$config->serviceUrl = Yii::$app->params["hppUrl"];

		$service = new HostedService($config);

		$post = Yii::$app->request->post();
		$sucess = false;
		$responseJson = $post['hppResponse'];
		try {
		   $parsedResponse = $service->parseResponse($responseJson, true);
		   $model = Transaction::findOne($id);
		   //print_r($parsedResponse->responseCode); die;
		   if(($model) && ($parsedResponse->responseCode == 00)){
		   	$model->status = $parsedResponse->responseMessage;
		   	$model->order_id = $parsedResponse->responseValues['ORDER_ID'];
		   	$model->sha1hash = $parsedResponse->responseValues['SHA1HASH'];
		   	$model->save();
		   	$sucess = true;
		   }
		} catch (ApiException $e) {
		
		}

		return $this->render('status',['sucess' => $sucess, 'parsedResponse' => $parsedResponse]);
    }

    private function generateHash($data, $secret)
	{

	    $toHash = [];
	    $timeStamp           = !isset($data['TIMESTAMP']) ? "" : $data['TIMESTAMP'];
	    $merchantId          = !isset($data['MERCHANT_ID']) ? "" : $data['MERCHANT_ID'];
	    $orderId             = !isset($data['ORDER_ID']) ? "" : $data['ORDER_ID'];
	    $amount              = !isset($data['AMOUNT']) ? "" : $data['AMOUNT'];
	    $currency            = !isset($data['CURRENCY']) ? "" : $data['CURRENCY'];
	    $payerReference      = !isset($data['PAYER_REF']) ? "" : $data['PAYER_REF'];
	    $paymentReference    = !isset($data['PMT_REF']) ? "" : $data['PMT_REF'];
	    $hppSelectStoredCard = !isset($data['HPP_SELECT_STORED_CARD']) ? "" : $data['HPP_SELECT_STORED_CARD'];
	    $payRefORStoredCard  = empty($hppSelectStoredCard) ?  $payerReference : $hppSelectStoredCard;

	    if (isset($data['CARD_STORAGE_ENABLE']) && $data['CARD_STORAGE_ENABLE'] === '1') {
	        $toHash = [
	            $timeStamp,
	            $merchantId,
	            $orderId,
	            $amount,
	            $currency,
	            $payerReference,
	            $paymentReference,
	        ];
	    } elseif ($payRefORStoredCard && empty($paymentReference)) {
	        $toHash = [
	            $timeStamp,
	            $merchantId,
	            $orderId,
	            $amount,
	            $currency,
	            $payRefORStoredCard,
	            ""
	        ];
	    } elseif ($payRefORStoredCard && !empty($paymentReference)) {
	        $toHash = [
	            $timeStamp,
	            $merchantId,
	            $orderId,
	            $amount,
	            $currency,
	            $payRefORStoredCard,
	            $paymentReference,
	        ];
	    } else {
	        $toHash = [
	            $timeStamp,
	            $merchantId,
	            $orderId,
	            $amount,
	            $currency,
	        ];
	    }

	    return sha1(sha1(implode('.', $toHash)) . '.' . $secret);
	}
}

views/payment/card-holder.php
<?php

use yii\helpers\Url;

$this->title = 'Tommy French';
?>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <button class="btn-primary btn hide" type="submit" id="payButtonId" >Checkout</button>
  </div>
</div>
<?php $this->registerJsFile(Yii::$app->request->baseUrl.'/js/rxp-js.js',['depends' => [yii\web\JqueryAsset::className()]]); ?>
<?php
$hppUrl = Yii::$app->params["hppUrl"];
$redirectUrl = Url::to(["/payment/process-payment", 'id' => $model->id],true);
$script = <<< JS
   RealexHpp.setHppUrl('$hppUrl');
    $(document).ready(function () {
            console.log("loaded", RealexHpp.lightbox);
            RealexHpp.lightbox.init("payButtonId", "$redirectUrl", $data);

            console.log( $('#payButtonId'));
            $('body').addClass('loaded');
            $('#payButtonId').trigger('click');
    });
JS;

$this->registerJs($script);
?>

views/payment/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/payment/index.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Url;
use yii\bootstrap\Alert;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
?>


<div class="container ">
    <div class="wrapper-content">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <span style="font-size:14px; color:#fff;">Please enter your details below in order to deposit with us. If you do not have an account already, please call us before making any deposits. 028 3832 2420</span>

            </div>
        </div>
    </div>
</div>
        
<div class="container ">
    <div class="wrapper-content">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="well well-sm">
               
                 <?php $form = ActiveForm::begin(["action" => Url::to(["/payment/data-post"],true), "method" => "post", "id" => "payment-form"]); ?>                                    
                        <div class="row">
                            <div class="col-md-12">
                                <h3 class="heading">
                                    Payment Detail
                                </h3>
                                <div class="form-group">
                                    <label for="name">
                                        Name
                                    </label>
                                    <input class="form-control" id="Name" name="Name" type="text" value="" required>     
                                </div>

                                <div class="form-group">
                                    <label for="Email">
                                        Email(Optional)
                                    </label>
                                    <input class="form-control" id="Email" name="Email" type="email" value="">

                                </div>

                                <div class="form-group">
                                    <label for="Phone">
                                        Phone Number(Optional)
                                    </label>
                                    <input class="form-control" id="PhoneNumber" name="PhoneNumber" type="number" value="">
                                    

                                </div>
                                <div class="form-group">
                                    <label for="AccountReference">
                                        Account Reference
                                    </label>
                                    <input class="form-control" id="ORDER_ID" name="ORDER_ID" type="text" value="" required>         

                                </div>
                                <div class="form-group">
                                    <label for="totalamount">
                                        Total Amount(in whole pounds only e.g. 25.00)
                                    </label>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <span class="">£</span>
                                        </span>
                                        <input class="form-control" id="AMOUNT" name="AMOUNT" type="text" value="0">
                                        
                                    </div>
                                </div>
                                <input id="AccountRefference" name="AccountRefference" type="hidden" value="">
                                <input id="CURRENCY" name="CURRENCY" type="hidden" value="EUR">
                                <input id="SHA1HASH" name="SHA1HASH" type="hidden" value="">
                                <input id="AUTO_SETTLE_FLAG" name="AUTO_SETTLE_FLAG" type="hidden" value="1">
                                <input id="TIMESTAMP" name="TIMESTAMP" type="hidden" value="">
                                
                                <div class="form-group">
                                    <label for="comments">
                                        Comments
                                    </label>

                                    <textarea class="form-control" cols="25" id="Comments" name="Comments" rows="9"></textarea>
                                </div>

                            </div>

                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary pull-right" id="btnPaynow">
                                    Pay Now
                                </button>
                            </div>
                        </div>
                    <?php ActiveForm::end(); ?>                              
               
                </div>
            </div>

        </div>
    </div>
</div>

views/payment/payment.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Url;
use yii\bootstrap\Alert;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Redirecting';
?>

<div class="main-page form-page page-min-height page-pt page-pb page-mb-n">
        <div class="container">
           <div class="row">
            <div class="col-lg-6 col-md-8 offset-lg-3 offset-md-2 pt-2 pt-md-3">
              <div class="card mt-3 mb-4">
                <div class="card-header">
                  <h3>Message</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                      <h3 style="margin-left: 30px">Page redirecting to payment.</h3>
                   </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="/dist/rxp-js.js"></script>
<script>
    RealexHpp.setHppUrl('https://pay.sandbox.realexpayments.com/pay');
    // get the HPP JSON from the server-side SDK
    // $(document).ready(function () {
        $.post("/payment/data-post", function (jsonFromServerSdk) {
            RealexHpp.redirect.init("btnPaynow","https://dev.rlxcarts.com/mobileSDKsV2/response.php", jsonFromServerSdk);
            $('body').addClass('loaded');
        });
    // });
</script>

views/payment/status.php
<?php

use yii\helpers\Url;

?>
                    
<div class="container" style="position: fixed;top: 50%;left: 50%;transform: translate(-50%, -50%);">
    <div class="wrapper-content">
        <div class="row justify-content-center">
            <div class="col-md-6 col-md-offset-3">
                <div>  
                    <?php if($sucess == true) { ?>
                        <div class="text-center alert alert-success p-20">
                            <p style="font-size:14px; line-height: 1.5em; font-weight: 400; margin-bottom: 15px">
                             <strong>Successful – The transaction has been authorized successfully.</strong></p>
                            <a href="http://www.tommybet.co.uk/" class="btn btn-success mr-1 mt-3">
                              <span>Ok</span>
                            </a>    
                        </div>
                        
                    <?php } else{ ?> 
                        <div class="text-center alert alert-danger p-20">
                            <p style="font-size:14px; line-height: 1.5em; font-weight: 400;">Error : <?= str_replace("[ test system ] ","",$parsedResponse->responseMessage) ?></p>
                            <a href="http://www.tommybet.co.uk/" class="btn btn-danger mr-1 mt-3 ">
                              <span>Ok</span>
                            </a>   
                        </div>
                         
                    <?php }?>
                </div>
            </div>
        </div>
    </div>
</div>
          